### ISSUE TITLE
Please document generating coverage for mulitple directories

### ISSUE THREAD

**Issue by jbowtie** [codecov/example-go#1]
Normally you can test an entire source tree using `go test ./...` (which means run tests in the current package and all subdirectories)

However, as can be seen [here](https://travis-ci.org/jbowtie/ratago/builds/61709070#L127) when you invoke the go test tool with coverage flags you get "cannot use test profile flag with multiple packages".

Can we generate and upload multiple coverage files? Is there an alternative go tool that does the right thing? Is there a combination of flags that will generate coverage of multiple packages? It's unclear to me how this should be fixed.

**Comment by stevepeak** [comment]
@jbowtie can you try to run your CI with this command:

```shell
go test -covermode=atomic ./...
find .
bash <(curl -s https://codecov.io/bash)
```

Lets see what files are being generated. Codecov can automatically find all the coverage files and append them together. [See here](https://github.com/codecov/codecov-bash/blob/1e3f6056c4ec9764682e2feefde2f6f36e2dd1e1/codecov#L245-L251). When you try this out send me the Travis build to inspect. Thanks!

**Comment by jbowtie** [comment]
Travis is offline at the moment, will link it here when it comes back online.

I have a fallback plan if that doesn't work out - now that I know I can simply generate multiple files and they'll be found, I can run the tests in each individual subdir needed.

**Comment by stevepeak** [comment]
I checked out the Travis build... that did not look like it worked. Here is what another customer did that I thought of justnow.

https://github.com/resal81/molkit/blob/master/scripts/coverage.sh

**Comment by jbowtie** [comment]
@stevepeak The [Travis build](https://travis-ci.org/jbowtie/ratago/builds/62152835) has finished. No coverage reports were generated.

Unless you have a better solution I'll just manually generate a coverage report for each subdirectory that includes tests and trust that the script will pick them up.

**Comment by stevepeak** [comment]
@jbowtie did you checkout https://github.com/resal81/molkit/blob/master/scripts/coverage.sh ?

**Comment by jbowtie** [comment]
@stevepeak Yes, our notifications are overlapping.  :smile: I'll implement that or something substantially similar per the updated README soon. Thanks for documenting a workaround so quickly.

**Comment by stevepeak** [comment]
Your very welcome. Thank you for being patient. Let me know if this works and how to improve upon it. Cheers!
